### ISSUE TITLE
Peer Review - Add Diagram for System Boundaries and Components in Hazard analysis doc (optional)

### ISSUE THREAD

**Issue by MohammadMohsinKhan** [TPGEngine/tpg#129]
**Artifact Under Review**
Hazard analysis - section 3

**Team Number for Team Doing the Review**
Team 2

**Description of Issue**
Add Diagram for System Boundaries and Components. This can be in the form of a UML diagram for example and serves as an aid for readers to understand better.
Note: this is not part of the rubric but is a good addition!

**Comment by cyrussamante** [comment]
As discussed with our TA, we will not proceed with this issue. Thank you for the review!
